name: cloud-function-deploy

on: 
  push:
    branches: [main]
    paths: 
      - 'function/**'
      - '.github/workflows/cloud-function-deploy.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./function
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p /home/runner/.npm
      continue-on-error: true

    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: 'npm'
        cache-dependency-path: function/package-lock.json
  
    
    - name: npm install
      run: npm install
      # setting https://github.com/serverless/serverless-tencent/issues/142
    - name: echo >.env
      run: echo 'SLS_GEO_LOCATION=cn serverless deploy'>./.env && echo 'SERVERLESS_PLATFORM_VENDOR=tencent'>>./.env && cat ./.env
    - name: npm install serverless
      run: npm i -g serverless serverless-tencent
    - name: install typescript
      run: npm install -g typescript
    - name: login with key
      run: serverless credentials set --secretId ${{ secrets.TENCENT_SECRET_ID }} --secretKey ${{ secrets.TENCENT_SECRET_KEY }}
    - name: build
      run: npm run build
    - name: deploy
      run: sls deploy
