name: cloud-function-eslint

on:
  push:
    branches: [ main ]
    paths:
      - 'functions/**'
  pull_request:
    paths:
      - 'functions/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./function/
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p /home/runner/.npm
      continue-on-error: true

    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: npm install
      run: npm install
    - name: npm install eslint
      run: npm install eslint -g
    - name: eslint-plugin-import@latest
      run: npm install eslint-plugin-import@latest --save-dev
    - name: eslint fix
      run: npm run fix
    - name: build
      run: npm run build

